SEED: 123
STEP_SIZE: 0.00512
NUM_SAMPLES: 200
# NUM_SAMPLES: 10 # For DEBUG
LEAP_STEP: 20
OMEGA: 10
SOFTABS_CONST: 1.0E+06
JITTER: 0.001
DIMENSION: 10
BASEMODEL : 'blr'
BNN_LOSS_TYPE : 'binary_class_linear_output'
BNN_DATASET : 'gm'
BNN_LAYER_SIZES : [2, 1]
BNN_NUM_TRAIN : 6
BNN_NUM_VAL : 300
TAU_OUT : 100.
TAU_OUT_VAL : 1.
DEBUG: TRUE


  