SEED: 0
STEP_SIZE: 0.0005
NUM_SAMPLES: 200
# NUM_SAMPLES: 10 # For DEBUG
LEAP_STEP: 30
OMEGA: 10
SOFTABS_CONST: 1.0E+06
JITTER: 0.001
DIMENSION: 10
BASEMODEL : 'bnn'
BNN_LOSS_TYPE : 'regression'
BNN_DATASET : 'agw'
BNN_LAYER_SIZES : [1, 100, 100, 1]
BNN_NUM_TRAIN : 6
BNN_NUM_VAL : 300
TAU_OUT : 110.4439498986428
TAU_OUT_VAL : 110.4439498986428
DEBUG: TRUE


  